version: '3.8'
services:
  postgres:
    image: postgres:14.3-alpine3.15
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_secret_file
      POSTGRES_DB: ${PG_NAME}
      DATABASE_HOST: ${PG_HOST}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database-config:/etc/postgresql
      - database-postgres:/var/lib/postgresql/data
    networks:
      - database
      - backend
    secrets:
      - pg_secret_file

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    secrets:
      - pg_secret_file
    networks:
      - database

  redis:
    image: redis:7.0.0-alpine3.15
    container_name: redis_cache
    restart: on-failure
    volumes:
      - cache-redis:/data
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  database-config:
  database-postgres:
  cache-redis:


networks:
  database:
    driver: bridge
  backend:
    driver: bridge

secrets:
  pg_secret_file:
    file: pg_secret.txt
